# :base_url = https://k8s.amaris.ovh:30446
# :base_url = http://k8s.amaris.ovh:30080/mon-compte-connector/clj
:base_url = http://localhost:8080
:user_mail = user11@domain1.com
:user_pass = Password11
:user_basic = dXNlcjExQGRvbWFpbjEuY29tOlBhc3N3b3JkMTE=
:device-uid = yrn8932n7m0rx49t048x80t35300
:token = eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoidXNlcjExQGRvbWFpbjEuY29tIiwidWlkIjoidXMxMSIsImV4cCI6MTUzNjc3NDE0OX0.6-NiY8RbLLW5i6gecyt1ldpzB99M4VVLD8gSueCd-fs
:base_headers = <<
Content-Type: application/json
X-MyAccountApp-Build-ID: #appVersionSnapshot
X-MyAccountApp-Device-ID: :device-uid
#

# API version

GET :base_url/
:base_headers

# API description

GET :base_url/v1
:base_headers

# Create auth token

POST :base_url/v1/auth/token
:base_headers
Authorization: Basic :user_basic

# Create auth token - mail invalid

POST :base_url/v1/auth/token
:base_headers
Authorization: Basic dXNlcjGRvbWFpbjEuY29tOlBhc3N3b3JkMTE=

# Create auth token - not found

POST :base_url/v1/auth/token
:base_headers
Authorization: Basic dXNlckBkb21haW4xLmNvbTpQYXNzd29yZDEx

# Create auth token - invalid credentials

POST :base_url/v1/auth/token
:base_headers
Authorization: Basic dXNlcjExQGRvbWFpbjEuY29tOlBhc3JkMTE=

# Get user info

GET :base_url/v1/me
:base_headers
Authorization: Bearer :token

# Get user info - invalid auth header

GET :base_url/v1/me
:base_headers
Authorization: toto

# Get user info - invalid token

GET :base_url/v1/me
:base_headers
Authorization: Bearer nciwpinuicpuivhfyuvh

# Change user password

PUT :base_url/v1/me/password
:base_headers
Authorization: Bearer :token

{
  "oldPassword": "Password11",
  "newPassword": "NewPassword11"
}

# Change user password - invalid auth header

PUT :base_url/v1/me/password
:base_headers
Authorization: toto

{
  "oldPassword": "Password11",
  "newPassword": "NewPassword11"
}

# Change user password - invalid token

PUT :base_url/v1/me/password
:base_headers
Authorization: Bearer nciwpinuicpuivhfyuvh

{
  "oldPassword": "Password11",
  "newPassword": "NewPassword11"
}

# Change user password - missing password

PUT :base_url/v1/me/password
:base_headers
Authorization: Bearer :token

{}

# Change user password - invalid old password

PUT :base_url/v1/me/password
:base_headers
Authorization: Bearer :token

{
  "oldPassword": "toto",
  "newPassword": "NewPassword11"
}

# Change user password - invalid new password

PUT :base_url/v1/me/password
:base_headers
Authorization: Bearer :token

{
  "oldPassword": "NewPassword11",
  "newPassword": "Password11"
}

# Get Reset code

POST :base_url/v1/reset/code
:base_headers

{
  "mail": "user22@domain2.com"
}

# Get Reset code - not found

POST :base_url/v1/reset/code
:base_headers

{
  "mail": "undefined@domain2.com"
}

# Get OTT

POST :base_url/v1/reset/token
:base_headers

{
  "mail": "user22@domain2.com",
  "code": 445004
}

# Reset password

POST :base_url/v1/reset/password
:base_headers

{
  "mail": "user22@domain2.com",
  "OTT": "eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoidXNlcjIyQGRvbWFpbjIuY29tIiwiZXhwIjoxNTM2Nzc1MzkwfQ.iG6rkPW812zvujAHNtLI7fz2DmB-KOpMFv__Se5-0M4",
  "newPassword": "hello"
}
